from .cnn_neighbors_hypermodel import *
from .cnn_lin_svm_hypermodel import *
from .cnn_rbf_svm_hypermodel import *
from .cnn_gaussian_process_hypermodel import *
from .cnn_decision_tree_hypermodel import *
from .cnn_random_forest_hypermodel import *
from .cnn_adaboost_hypermodel import *
from .cnn_naive_bayes_hypermodel import *
from .cnn_qda_hypermodel import *
from .cnn_classic_hypermodel import *
